name: Prepare a GitHub release note

on:
  push:
    branches:
      - released

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  preparation:
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Get version name
        id: meta
        run: |
          version=$(cat .version)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create draft release notes
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.meta.outputs.version }}
        run: |
          git tag "$VERSION"
          git push origin "$VERSION"
          gh release create "$VERSION" --draft --generate-notes --title "$VERSION"
